---
name: Auto Tag and Release
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: "0"

      - id: auto-tag
        name: "Bump/tag version"
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
          INITIAL_VERSION: "0.0.1"
      - run: echo "$(git rev-parse --short HEAD) >> mylastcommit.txt
      
      - run: cat mylastcommit.txt
      
      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.auto-tag.outputs.new_tag }}
          bodyFile: "RELEASE_NOTES.md"
          token: ${{ secrets.GITHUB_TOKEN }}
